_base: "./base.yaml"

log:
  comment: "coco"

data:
  train_l:
    dataset: "COCO"
    prefetch: False
    infinity_sampler: True
    grouped_sampler: True
    cache: "./cache/coco17_train01_1.dict"
    num_workers: 4
    batch_size: 1
    shuffle: True
    img_transforms:
    batch_transforms:
      batch_apply:
        random_horizontal_flip:
        resize:
          - [400, 1200]
          - 1333
          - "range"
  train_u:
    dataset: "COCO"
    prefetch: False
    infinity_sampler: True
    grouped_sampler: True
    cache: "./cache/coco17_train99_1.dict"
    num_workers: 4
    batch_size: 4
    shuffle: True
    img_transforms:
    batch_transforms:
      batch_apply:
        random_horizontal_flip:
        resize:
          - [400, 1200]
          - 1333
          - "range"
  test:
    dataset: "COCO"
    prefetch: False
    infinity_sampler: False
    grouped_sampler: False
    cache: "./cache/coco_instances_val2017.dict"
    json_file: "./data/COCO2017/annotations/instances_val2017.json"
    num_workers: 4
    batch_size: 1
    shuffle: False
    img_transforms:
    batch_transforms:
      batch_apply:
        resize:
          - 800
          - 1333
        normalize:
      batch_pad:
