_base: "./base.yaml"

log:
  comment: "voc"

evaluator: "voc"

data:
  train:
    dataset: "VOC"
    prefetch: False
    infinity_sampler: True
    grouped_sampler: True
    cache: "./cache/voc07_trainval.dict"
    num_workers: 4
    batch_size: 4
    shuffle: True
    img_transforms:
    batch_transforms:
      batch_apply:
        random_horizontal_flip:
        resize:
          - [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
          - 1333
        normalize:
      batch_pad:
  test:
    dataset: "VOC"
    prefetch: False
    infinity_sampler: False
    grouped_sampler: True
    cache: "./cache/voc07_test.dict"
    json_file: "./cache/voc07_test_cocostyle.json"
    num_workers: 4
    batch_size: 1
    shuffle: False
    img_transforms:
    batch_transforms:
      batch_apply:
        resize:
          - 600
          - 1000
        normalize:
      batch_pad:

model:
  roihead:
    num_classes: 20

solver:
  iter_num: 18000
  ckp_interval: 5000
  lr: 0.02
  weight_decay: 0.0001
  momentum: 0.9
  lr_steps: [12000, 16000]
  lr_gamma: 0.1
  warmup: True
  warmup_gamma: 0.001
  warmup_steps: 100
