dev_mode: False
seed: 669
operator: "fasterrcnn"
evaluator: "coco"

log:
  prefix: "fasterrcnn"
  comment: "full"
  log_dir: "./log/"
  summary_interval: 20
  wandb: "FasterRCNN"
  aim:

model:
  backbone:
    name: "resnet50"
    pretrained: True
    trainable_layers: 3
  rpn:
    pre_nms_topk_train: 2000
    post_nms_topk_train: 1000
    pre_nms_topk_test: 1000
    post_nms_topk_test: 1000
    nms_threshold: 0.7
  roihead:
    num_classes: 80
  score_threshold: 0.05
  nms_threshold: 0.5
  max_detections: 100

solver:
  iter_num: 90000
  ckp_interval: 5000
  lr: 0.02
  weight_decay: 0.0001
  momentum: 0.9
  lr_steps: [60000, 80000]
  lr_gamma: 0.1
  warmup: True
  warmup_gamma: 0.001
  warmup_steps: 1000

distributed:
  use: False
